# Generated by Django 3.1.7 on 2021-03-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('power', models.IntegerField(default=100)),
            ],
        ),
    ]
