# Generated by Django 3.1.7 on 2021-03-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guard', '0002_datadb'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadb',
            name='time',
            field=models.CharField(default='', max_length=20),
        ),
    ]
