# Generated by Django 3.1.7 on 2021-03-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guard', '0003_datadb_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='datadb',
            name='time',
        ),
    ]
