# Generated by Django 3.1.7 on 2021-03-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guard', '0004_auto_20210312_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadb',
            name='working',
            field=models.IntegerField(default=0),
        ),
    ]
